"""Pydantic data models for structured outputs across research agents."""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class SubTopic(BaseModel):
    """Represents an individual analytical pillar or research subtask."""
    title: str = Field(..., description="Concise title of the subtopic")
    description: str = Field(..., description="Detailed research objective and scope for this subtopic")
    search_queries: List[str] = Field(default_factory=list, description="Specific, targeted search queries to find data for this subtopic")
    key_questions: List[str] = Field(default_factory=list, description="Key analytical questions this subtopic must answer")


class ResearchPlan(BaseModel):
    """Structured research plan produced by the Lead Planner Agent."""
    topic: str = Field(..., description="The original or refined research topic")
    overview: str = Field(..., description="Executive overview of the research scope and goals")
    target_audience: str = Field(default="Researchers and Technical Practitioners", description="Target audience and depth level")
    subtopics: List[SubTopic] = Field(default_factory=list, description="List of decomposed subtopics to investigate")
    expected_outcomes: List[str] = Field(default_factory=list, description="Key outcomes, hypotheses, or deliverables expected from this research")


class SourceDocument(BaseModel):
    """Represents a verified piece of evidence retrieved from search tools."""
    id: int = Field(..., description="Unique integer citation ID (e.g. 1 for [1])")
    title: str = Field(..., description="Title of the article, paper, or webpage")
    url: str = Field(..., description="Direct URL or identifier of the source")
    snippet: str = Field(..., description="Concise summary or excerpt of relevant evidence")
    content: Optional[str] = Field(None, description="Full scraped or extracted text content if available")
    source_type: str = Field("web", description="Source origin type: 'web', 'arxiv', 'wikipedia', or 'tavily'")
    authors: Optional[List[str]] = Field(default_factory=list, description="Authors of the academic paper or article if known")
    published_date: Optional[str] = Field(None, description="Publication date if available")
    relevance_score: float = Field(0.8, description="Relevance score between 0.0 and 1.0")


class SectionDraft(BaseModel):
    """Draft for a single section generated by the Research Writer Agent."""
    section_title: str = Field(..., description="Section heading title")
    content: str = Field(..., description="Detailed synthesized markdown content with bracket citations like [1], [2]")
    citations_used: List[int] = Field(default_factory=list, description="List of source IDs cited in this section")
    key_findings: List[str] = Field(default_factory=list, description="Bullet points of key takeaways from this section")


class ReviewFeedback(BaseModel):
    """Evaluation report from the Fact-Checker and Reviewer Agent."""
    is_approved: bool = Field(..., description="True if the report meets quality standards, False if revision is required")
    overall_score: float = Field(..., description="Quality score from 1.0 to 10.0")
    critique: str = Field(..., description="Summary of strengths and weaknesses")
    factual_accuracy_notes: str = Field(..., description="Assessment of citation grounding and factual fidelity")
    missing_aspects: List[str] = Field(default_factory=list, description="Critical gaps or unaddressed subtopics")
    suggested_refinements: List[str] = Field(default_factory=list, description="Actionable instructions for revision")
    revision_needed: bool = Field(False, description="Flag to trigger another agent loop")


class FinalReport(BaseModel):
    """Complete structured research report ready for display and export."""
    title: str = Field(..., description="Title of the comprehensive research report")
    topic: str = Field(..., description="Original research topic")
    executive_summary: str = Field(..., description="High-impact executive summary")
    key_takeaways: List[str] = Field(default_factory=list, description="Major overarching insights from the research")
    table_of_contents: List[str] = Field(default_factory=list, description="List of report sections")
    sections: List[SectionDraft] = Field(default_factory=list, description="Synthesized report sections")
    future_outlook: str = Field("", description="Future research directions, emerging trends, or strategic implications")
    methodology_notes: str = Field("", description="Notes on sources examined, search strategy, and multi-agent synthesis")
    sources: List[SourceDocument] = Field(default_factory=list, description="All referenced sources cataloged with citation IDs")
    generation_timestamp: str = Field(..., description="ISO timestamp of report completion")
    total_words: int = Field(0, description="Approximate total word count of the report")
    review_summary: Optional[str] = Field(None, description="Summary of review and quality verification")


class QAResponse(BaseModel):
    """Response model for interactive follow-up questions."""
    answer: str = Field(..., description="Direct, grounded answer to the user's question")
    sources_referenced: List[int] = Field(default_factory=list, description="Source IDs cited in the answer")
    confidence_score: float = Field(0.9, description="Confidence score between 0.0 and 1.0")
